branches:
  only:
  - master
  - develop

os:
  - linux
  - osx

language: java
jdk:
  - oraclejdk8
  - openjdk8

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gradle asemble; fi
  #- gradle assemble

script:
  - gradle check
