branches:
  only:
  - master
  - develop

os:
  - linux
  - osx

language: java
jdk:
  - oraclejdk8
  - openjdk8

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew assemble; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gradle assemble; fi
    #- gradle assemble

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./gradlew check; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then gradle check; fi
    #- gradle check
