branches:
  only:
  - master
  - develop

os:
  - linux
  - osx

language: java
jdk:
  - oraclejdk8
  - openjdk8

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gradle; fi
  - gradle assemble

script:
  - gradle check
